### ISSUE TITLE
Text für Benutzer registrieren

### ISSUE THREAD

**Issue by simonline** [sinnwerkstatt/common-good-online-balance#33]
Liebe/r Nutzer_in, Liebe/r Matrix Interessierte_r,
bei diesem Schritt können Sie Ihr personenbezogenes Profil anlegen. Es ist unabhängig vom Firmenprofil. Ihr personenbezogenes Profil können bzw. müssen Sie bei dem nächsten Schritt mit Ihrer Firma verbinden. Die Trennung von Firma und Person ermöglicht eine Zuordnung von mehreren Personen aus ihrer Firma zu dem Personenkreis, der sich um die Erstellung der Bilanz kümmert.

**Comment by Thomas-De** [comment]
Hi Simon,
Text kann so bleiben, ist abgenommen.
LG
Thomas
