### ISSUE TITLE
Text für Unternehmensliste in Benutzerprofil

### ISSUE THREAD

**Issue by simonline** [sinnwerkstatt/common-good-online-balance#34]
Falls Sie noch kein Unternehmensprofil erstellt haben, können Sie es  hier machen: ‚Unternehmen erstellen‘. Wenn Sie bereits eine Unternehmensprofil erstellt haben, klicken Sie auf: ‚Unternehmen beitreten‘. Wenn Sie erstmalig Ihr Unternehmensprofil erstellen, müssen Sie von einem Administrator freigegeben werden, die Freigabe bekommen Sie dann innerhalb von 3 Tagen. Falls dies nicht geschehen sollte oder die Eintragung dringlich ist, melden Sie sich bitte bei: S.T@gwö.org

**Comment by Thomas-De** [comment]
Hi Simon,
Susanne hatte oben einen Platzhalter für ihre E-Mail-Adresse eingegeben. Kannst Du die o.g. Adresse durch Susanne.Traumann@ecogood.org erstzen? Damit ist der Text dann von uns abgenommen.
LG
Thomas
