### ISSUE TITLE
Felder und Hilfetexte für Unternehmen

### ISSUE THREAD

**Issue by simonline** [sinnwerkstatt/common-good-online-balance#35]
- Bild: „Logo“
- Standort: entweder raus oder Hilfetext „Zur Darstellung Ihrer Firma auf einer Karte ist hier eine Eintragung notwendig. Bitte tragen sie hier den Standort ein, für die Bilanz erstellt wird. In einem folgenden Feld können Sie auswählen welche Elemente dargestellt werden.“
- Industrie: „Branche“
- Sichtbarkeit: zusätzlich „Logo, Name, Website, Ansprechpartner/GF, Telefonnummer“

**Comment by Thomas-De** [comment]
Hi Simon,
bitte das Feld "Standort" entfernen.
LG
Thomas
